name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check secrets visibility
        run: |
          echo "METRICS_TOKEN length: $(echo -n '${{ secrets.METRICS_TOKEN }}' | wc -c)"
          echo "github.token length: $(echo -n '${{ github.token }}' | wc -c)"

      - name: Resolve token
        run: |
          if [ -n "${{ secrets.METRICS_TOKEN }}" ]; then
            echo "TOKEN_RESOLVED=${{ secrets.METRICS_TOKEN }}" >> "$GITHUB_ENV"
            echo "Using METRICS_TOKEN (PAT)"
          else
            echo "TOKEN_RESOLVED=${{ github.token }}" >> "$GITHUB_ENV"
            echo "Using github.token (fallback)"
          fi

      - name: Confirm resolved token length
        run: |
          echo "Resolved token length: $(echo -n "$TOKEN_RESOLVED" | wc -c)"

      - name: Generate GitHub metrics
        uses: radiaku/metrics@master
        with:
          token: ${{ env.TOKEN_RESOLVED }}       # normal Actions input
          
        env:
          # Make sure ANY code path finds the token
          INPUT_TOKEN: ${{ env.TOKEN_RESOLVED }}
          GITHUB_TOKEN: ${{ env.TOKEN_RESOLVED }}
          GH_TOKEN: ${{ env.TOKEN_RESOLVED }}
      
          # --- Core inputs forced via INPUT_* (so getInput('...') will see them) ---
          INPUT_USER: radiaku
          INPUT_TEMPLATE: classic
          INPUT_CONFIG_TIMEZONE: Asia/Jakarta
      
          # Don't kill the whole run when a plugin fails
          INPUT_PLUGINS_ERRORS_FATAL: 'no'
      
          # ✅ enable only stable, API-based plugins
          INPUT_PLUGIN_ISOCALENDAR: 'yes'
          INPUT_PLUGIN_LANGUAGES: 'yes'
          INPUT_PLUGIN_STARGAZERS: 'yes'
          INPUT_PLUGIN_FOLLOWUP: 'yes'
      
          # ❌ hard-disable Puppeteer / flaky scrapers
          INPUT_PLUGIN_SUPPORT: 'no'
          INPUT_PLUGIN_SKYLINE: 'no'
          INPUT_PLUGIN_STARLISTS: 'no'
          INPUT_PLUGIN_TOPICS: 'no'
          INPUT_PLUGIN_PAGESPEED: 'no'
          INPUT_PLUGIN_ACHIEVEMENTS: 'no'
          INPUT_PLUGIN_ACTIVITY: 'no'
          INPUT_PLUGIN_DISCUSSIONS: 'no'
          INPUT_PLUGIN_TRAFFIC: 'no'
          INPUT_PLUGIN_GISTS: 'no'
          INPUT_PLUGIN_PROJECTS: 'no'
      
          # Optional: more visibility
          INPUT_DEBUG: 'yes'
