name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check secrets visibility
        run: |
          echo "METRICS_TOKEN length: $(echo -n '${{ secrets.METRICS_TOKEN }}' | wc -c)"
          echo "github.token length: $(echo -n '${{ github.token }}' | wc -c)"

      - name: Resolve token
        run: |
          if [ -n "${{ secrets.METRICS_TOKEN }}" ]; then
            echo "TOKEN_RESOLVED=${{ secrets.METRICS_TOKEN }}" >> "$GITHUB_ENV"
            echo "Using METRICS_TOKEN (PAT)"
          else
            echo "TOKEN_RESOLVED=${{ github.token }}" >> "$GITHUB_ENV"
            echo "Using github.token (fallback)"
          fi

      - name: Confirm resolved token length
        run: |
          echo "Resolved token length: $(echo -n "$TOKEN_RESOLVED" | wc -c)"

      - name: Generate GitHub metrics
        uses: radiaku/metrics@master
        with:
          token: ${{ env.TOKEN_RESOLVED }}       # normal Actions input
          
          # required basics
          user: radiaku
          template: classic
          config_timezone: Asia/Jakarta
      
          # do not fail the job if a plugin errors
          plugins_errors_fatal: 'no'
      
          # ✅ stable, API-only plugins
          plugin_isocalendar: 'yes'
          plugin_languages: 'yes'
          plugin_stargazers: 'yes'
          plugin_followup: 'yes'
      
          # ❌ disable Puppeteer / heavy scrapers for now
          plugin_skyline: 'no'
          plugin_support: 'no'
          plugin_starlists: 'no'
          plugin_topics: 'no'
          plugin_pagespeed: 'no'
          plugin_achievements: 'no'
          plugin_activity: 'no'
          plugin_discussions: 'no'
          plugin_traffic: 'no'
          plugin_gists: 'no'
          plugin_projects: 'no'
          
        env:
          # make sure ANY reader code will find it:
          INPUT_TOKEN: ${{ env.TOKEN_RESOLVED }} # what core.getInput('token') reads
          GITHUB_TOKEN: ${{ env.TOKEN_RESOLVED }}# some forks read this directly
          GH_TOKEN: ${{ env.TOKEN_RESOLVED }}    # others read this
          # add your options here (if any)
          # METRICS_USER: radiaku
          # METRICS_TEMPLATE: classic
