name: Metrics

on:
  schedule:
    - cron: "0 0 * * 1"        # every Monday 00:00 UTC (weekly)
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # needed to commit the SVG

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Resolve token
        run: |
          if [ -n "${{ secrets.METRICS_TOKEN }}" ]; then
            echo "TOKEN=${{ secrets.METRICS_TOKEN }}" >> $GITHUB_ENV
          else
            echo "TOKEN=${{ github.token }}" >> $GITHUB_ENV
          fi

      - name: Generate metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ env.TOKEN }}
          user: radiaku
          template: classic
          filename: github-metrics.svg
          output_action: none              # <— prevent auto-commit
          plugins_errors_fatal: no
          plugin_isocalendar: yes
          plugin_languages:  yes
          plugin_stargazers: yes
          plugin_followup:   yes
          plugin_skyline:    no
          plugin_support:    no
          plugin_starlists:  no
          plugin_pagespeed:  no
          plugin_wakatime:   no
          plugin_activity:   no
      
      - name: Commit generated file
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics_renders/github-metrics.svg   # <— correct path
          git commit -m "chore: update metrics [skip ci]" || echo "no changes"
          git push
      
