name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Debug: show token visibility & choose the source (PAT preferred)
      - name: Sanity check secrets visibility
        run: |
          echo "METRICS_TOKEN length: $(echo -n '${{ secrets.METRICS_TOKEN }}' | wc -c)"
          echo "github.token length: $(echo -n '${{ github.token }}' | wc -c)"

      - name: Resolve token
        run: |
          if [ -n "${{ secrets.METRICS_TOKEN }}" ]; then
            echo "TOKEN_RESOLVED=${{ secrets.METRICS_TOKEN }}" >> "$GITHUB_ENV"
            echo "Using METRICS_TOKEN (PAT)"
          else
            echo "TOKEN_RESOLVED=${{ github.token }}" >> "$GITHUB_ENV"
            echo "Using github.token (fallback)"
          fi

      - name: Confirm resolved token length
        run: |
          echo "Resolved token length: $(echo -n "$TOKEN_RESOLVED" | wc -c)"

      - name: Generate GitHub metrics
        uses: radiaku/metrics@master
        with:
          token: ${{ env.TOKEN_RESOLVED }}        # INPUT_TOKEN for actions/core getInput('token')
        env:
          GITHUB_TOKEN: ${{ env.TOKEN_RESOLVED }} # process.env.GITHUB_TOKEN
          GH_TOKEN: ${{ env.TOKEN_RESOLVED }}     # some forks read this one
          # Add other options here if needed
          # METRICS_USER: radiaku
          # METRICS_TEMPLATE: classic
