name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:       # Allow manual trigger
  push:
    branches: ["master" ]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # allow the action to commit metrics updates

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub metrics (fallback test)
        uses: radiaku/metrics@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # ✅ built-in token for quick test
          # You can add custom config below, for example:
          # user: radiaku
          # template: classic
          # config_timezone: Asia/Jakarta
          # plugin_isocalendar: yes
          # plugin_languages: yes
          # plugin_followup: yes
          # plugin_stargazers: yes
